import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import logging
from datetime import datetime
from apscheduler.schedulers.asyncio import AsyncIOScheduler
from sqlalchemy import select

from app.db import AsyncSessionLocal, AgentReportingSettings
from app.agents.agent_workflow import run_agent_workflow

logger = logging.getLogger("scheduler")

scheduler = AsyncIOScheduler()

async def send_report_email(to_email: str, pdf_path: str):
    """Sends the PDF report via email using SMTP credentials from .env"""
    mail_host = os.getenv("MAIL_HOST", "smtp.gmail.com")
    mail_port = int(os.getenv("MAIL_PORT", 587))
    mail_user = os.getenv("MAIL_USERNAME")
    mail_pass = os.getenv("MAIL_PASSWORD")
    mail_from = os.getenv("MAIL_FROM", mail_user)

    if not all([mail_host, mail_user, mail_pass, to_email]):
        logger.error("Missing email configuration or recipient address. Cannot send report.")
        return

    msg = MIMEMultipart()
    current_time_str = datetime.now().strftime("%Y-%m-%d %H:%M")
    msg['Subject'] = f"[{current_time_str}] Daily MES Manufacturing Executive Summary Report"
    msg['From'] = mail_from
    msg['To'] = to_email

    body = MIMEText("Please find attached your automated daily production and resources report generated by MAI.")
    msg.attach(body)

    if pdf_path and os.path.exists(pdf_path):
        with open(pdf_path, "rb") as f:
            part = MIMEApplication(f.read(), Name=os.path.basename(pdf_path))
            part['Content-Disposition'] = f'attachment; filename="{os.path.basename(pdf_path)}"'
            msg.attach(part)
    else:
        logger.warning(f"PDF not found at {pdf_path}. Sending email without attachment.")

    try:
        server = smtplib.SMTP(mail_host, mail_port)
        server.starttls()
        server.login(mail_user, mail_pass)
        server.send_message(msg)
        server.quit()
        logger.info(f"Automated report email sent to {to_email}")
    except Exception as e:
        logger.error(f"Failed to send automated report email: {e}")

async def check_and_run_daily_report():
    """Scheduled job to check if it's time to run the daily report"""
    try:
        async with AsyncSessionLocal() as session:
            result = await session.execute(select(AgentReportingSettings))
            settings = result.scalars().first()

        if not settings or not settings.is_enabled or not settings.schedule_time:
            return

        # Get current time in HH:MM format
        today = datetime.now().date()
        current_time_str = datetime.now().strftime("%H:%M")
        
        # Check if the scheduled time matches the current minute, and it hasn't run today
        if settings.schedule_time == current_time_str and settings.last_run_date != today:
            logger.info(f"Triggering scheduled daily report for {settings.email} at {current_time_str}")
            
            # Update last_run_date immediately to prevent concurrent triggers if the server reloads
            async with AsyncSessionLocal() as session2:
                result = await session2.execute(select(AgentReportingSettings))
                settings_to_update = result.scalars().first()
                settings_to_update.last_run_date = today
                await session2.commit()
            
            # Execute the agent workflow (bypassing approval for automated jobs)
            workflow_result = await run_agent_workflow(settings.prompt, is_approved=True)
            
            # workflow_result["pdf_url"] is like "http://localhost:8000/reports/filename.pdf"
            # We need the local file path to attach it.
            pdf_filename = ""
            if workflow_result.get("pdf_url"):
                pdf_filename = workflow_result["pdf_url"].split("/")[-1]
            
            local_pdf_path = os.path.join("reports", pdf_filename)
            
            # Verify that the query returned real data before sending
            has_data = False
            if workflow_result.get("sql_result"):
                # sql_result is a list of dicts with 'rows' key
                has_data = any(res.get("rows", 0) > 0 for res in workflow_result["sql_result"])
                
            if not has_data:
                logger.warning(f"Automated report yielded no data or query failed. Aborting email send for {settings.email} to avoid empty PDF.")
                return
                
            if settings.email:
                await send_report_email(settings.email, local_pdf_path)
            else:
                logger.warning("Automated report generated but no recipient email configured.")

    except Exception as e:
        import traceback
        traceback.print_exc()
        logger.error(f"Error in daily report scheduled job: {e}")

def start_scheduler():
    # Run check_and_run_daily_report every minute to see if time matches
    scheduler.add_job(check_and_run_daily_report, "interval", minutes=1, id="daily_report_job", replace_existing=True)
    scheduler.start()
    logger.info("APScheduler started for automated daily reporting.")

def stop_scheduler():
    scheduler.shutdown()
